config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: %i{show}, shallow: true do
    member do
      get :following, :followers
    end
  end
  # ゲストユーザー
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :relationships, only: %i[create destroy]

  
  resources :posts, shallow: true do
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resources :tags, only: %i{index}

  # タイマー機能用ルーティング
  get 'timers/study' => 'timers#study'
  get 'timers/relax' => 'timers#relax'
  get 'timers/fitness' => 'timers#fitness'
  get 'timers/hobby' => 'timers#hobby'
  post 'timers/study' => 'timers#study_create'
  post 'timers/relax' => 'timers#relax_create'
  post 'timers/fitness' => 'timers#fitness_create'
  post 'timers/hobby' => 'timers#hobby_create'
end

app/models/relationship.rb
class Relationship < ApplicationRecord
      #フォローワーのユーザー
      belongs_to :follower, class_name: "User"
      #フォロー中ユーザー
      belongs_to :following, class_name: "User"
      #バリデーション
      validates :follower_id, presence: true
      validates :following_id, presence: true
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
  def create
    @user = User.find(params[:following_id])
    current_user.follow(@user)
  end

  def destroy
    @user = User.find(params[:id])
    current_user.unfollow(@user)
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow.html.erb
<% if user_signed_in? && @user != current_user %>
  <div id="follow-form">
    <% if current_user.following?(@user)%>
      <%= form_with(model: current_user, url: relationship_path(@user), method: :delete, remote: true) do |f| %>
        <%= f.submit "フォロー中", class:"cursor-pointer rounded-full w-full items-center text-center shadow px-4 py-2 bg-indigo-400 border border-indigo-400 border-opacity-100 text-white"%>
      <% end %>
    <% else %>
      <%= form_with(model: current_user, url: relationships_path, method: :post, remote: true) do |f| %>
        <%= hidden_field_tag :following_id, @user.id %>
        <%= f.submit "フォローする", class:"cursor-pointer rounded-full w-full items-center text-center shadow px-4 py-2 bg-white border border-indigo-400 border-opacity-100 text-indigo-400 hover:bg-indigo-400 hover:text-white" %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/relationships/create.js.erb
$("#follow-form").html("<%= j(render('relationships/follow')) %>");

app/views/relationships/destroy.js.erb
$("#follow-form").html("<%= j(render('relationships/follow')) %>");