config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: %i{show}, shallow: true do
    member do
      get :following, :followers
    end
  end
  # ゲストユーザー
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :relationships, only: %i[create destroy]

  
  resources :posts, shallow: true do
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resources :tags, only: %i{index}

  # タイマー機能用ルーティング
  get 'timers/study' => 'timers#study'
  get 'timers/relax' => 'timers#relax'
  get 'timers/fitness' => 'timers#fitness'
  get 'timers/hobby' => 'timers#hobby'
  post 'timers/study' => 'timers#study_create'
  post 'timers/relax' => 'timers#relax_create'
  post 'timers/fitness' => 'timers#fitness_create'
  post 'timers/hobby' => 'timers#hobby_create'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # UserモデルActiveHash
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :career
  belongs_to :gender
  # ジャンルの選択が「--」の時は保存できないようにする

  # Userモデルバリデーション制限
  with_options presence: true do
    validates :nickname, length: { maximum: 10 }
    validates :email, uniqueness: true,
                      format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+.)+[a-z]{2,})\z/i, message: 'に@を入力してください' }
    validates :password, length: { minimum: 6 }, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: "は英数字を含め半角で入力してください"}
    validates :career_id, :gender_id, numericality: { other_than: 1, message: 'を選択してください' }
  end

  # Userモデルアソシエーション
  has_one_attached :avatar
  validates :avatar, content_type: ['image/png', 'image/jpg', 'image/jpeg']
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :timers, dependent: :destroy
  # フォローアソシエーション
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  #フォローしているかを確認するメソッド
  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  #フォローするときのメソッド
  def follow(user)
    following_relationships.create(following_id: user.id)
  end

  #フォローを外すときのメソッド
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end  

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.nickname = "ゲストユーザー"
      user.password = SecureRandom.urlsafe_base64 + "1a"
      user.career_id = 17
      user.gender_id = 4
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i[update destroy]

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。'
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
    @posts = @user.posts.with_attached_feature_images.includes(:likes, :comments, :taggings).order('created_at DESC').page(params[:page]).per(6)
    
    # ユーザーのタイマー合計取得
    @study_timers = @user.timers.all.where(genre: ["ポモドーロ学習", "学生学習"])
    @relax_timers = @user.timers.all.where(genre: ["ボックス呼吸", "レムサイクル仮眠"])
    @fitness_timers = @user.timers.all.where(genre: ["HIITトレーニング", "ストレッチ・ヨガ"])
    @hobby_timers = @user.timers.all.where(genre: ["ゲーム", "趣味"])
    
    # いいね合計数取得
    @likes_count = 0
    @posts.each do |post|
      @likes_count += post.likes.length
    end
  end

  def following
    #@userがフォローしているユーザー
    @users = @user.following
    render 'show_follow'
end

def followers
    #@userをフォローしているユーザー
    @users = @user.followers
    render 'show_follower'
end

private

  def set_user
    @user  = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_posts.html.erb
<div class="flex flex-wrap -m-5 py-2">
  <% @posts.each do |post| %>
    <div class="p-2 md:w-1/3">
      <div class="h-full overflow-hidden rounded border">
        <span class="inline-flex float-right text-sm font-thin p-2 mx-auto"><%= post.created_at.strftime('%Y/%m/%d')%></span>
        <div class="flex items-center">
          <% if post.user.avatar.present? %>
            <%= link_to "/users/#{post.user.id}", title: "ユーザーページへ" do %>
              <%= image_tag post.user.avatar, class:"inline-flex items-center justify-center p-2 mx-auto w-16 h-16 rounded-full flex-shrink-0 object-cover object-center"%>
              <span class="title-font font-medium"><%= post.user.nickname %></span>
            <% end %>
          <% else %>
            <%= link_to "/users/#{post.user.id}", title: "ユーザーページへ" do %>
              <img alt="user" src="/images/user.jpeg" class="inline-flex p-2 w-16 h-16 rounded-full flex-shrink-0 object-cover object-center">
              <span class="title-font font-medium px-1"><%= post.user.nickname %></span>
            <% end %>
          <% end %>
        </div>

        <%= link_to post do %>    
          <% if post.feature_images.present? %>
            <%= image_tag post.feature_images[0], class:"lg:h-48 md:h-36 w-full object-cover object-center", alt:"blog"%>
          <% else %>
            <img class="lg:h-48 md:h-36 w-full object-cover object-center" src="https://dummyimage.com/720x400" alt="blog">
          <% end %>
        <% end %>

        <div class="pt-3 p-6">
          <%= render 'tags/tag_list', tag_list: post.tag_list %>
          <%= link_to post do %>
            <h1 class="title-font text-lg font-bold text-gray-900 mt-1 mb-3 whitespace-pre-wrap"><%= link_to post.title, post %></h1>
            <div class="overflow-auto h-20">
              <p class="leading-relaxed mb-3 whitespace-pre-wrap font-medium"><%= post.body %></p>
            </div>
          <% end %>
          <div class="flex items-center flex-wrap text-xl">
            <%= render 'likes/like', post: post %>
            <%= link_to post do %>
              <%= render 'comments/comment', post: post %>
            <% end %>
            <% if user_signed_in? && current_user.id == post.user_id %>
              <%= link_to edit_post_path(post), class: "mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none pr-3 py-1 hover:text-green-400", title:"編集" do %>
                <i class="fas fa-edit"></i>
              <% end %>
              <%= link_to post, method: :delete, data: { confirm: 'ほんとに削除しますか？' }, class: "inline-flex items-center leading-none hover:text-red-600", title:"削除" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="max-w-6xl m-auto">
 
 <div class="flex items-center justify-between py-4 my-8 border-b">
    <% if user_signed_in? && current_user.id == @user.id %>
      <h1 class="text-xl font-bold mb-0 text-gray-500">あなたのプロフィール</h1>
    <% else %>
      <h1 class="text-xl font-bold mb-0 text-gray-500"><%= @user.nickname %>さんのプロフィール</h1>
    <% end %>
  </div>
  
  <div class="flex item-center justify-center">
    <div class="bg-white shadow p-4 rounded lg:w-1/2">
      <div class="text-center mt-4">
        <p class="text-gray-600 font-bold"><%= @user.nickname %></p>
      </div>
      <div class="flex justify-center mt-4">
        <% if @user.avatar.present?%>
          <%= image_tag @user.avatar, class:"p-2 mx-auto w-24 h-24 rounded-full flex-shrink-0 object-cover object-center"%>
        <% else %>
          <img alt="user" src="/images/user.jpeg" class="p-2 mx-auto w-16 h-16 rounded-full flex-shrink-0 object-cover object-center">
        <% end %>
      </div>
      <div class="mt-6 flex justify-around text-center">
        <div>
          <p class="text-gray-700 font-bold"><%= @user.posts.length %></p>
          <p class="text-xs mt-2 text-gray-600 font-hairline">投稿</p>
        </div>
        <div>
          <p class="text-gray-700 font-bold"><%= @likes_count %></p>
          <p class="text-xs mt-2 text-gray-600 font-hairline">受信したいいね</p>
        </div>
        <div>
          <%= link_to following_user_path(@user.id) do %>
            <p class="text-gray-700 font-bold"><%= @user.following.length %></p>
            <p class="text-xs mt-2 text-gray-600 font-hairline">フォロー中</p>
          <% end %>
        </div>
        <div>
          <%= link_to followers_user_path(@user.id) do %>
            <p class="text-gray-700 font-bold"><%= @user.followers.length %></p>
            <p class="text-xs mt-2 text-gray-600 font-hairline">フォロワー</p>
          <% end %>
        </div>
      </div>
      
      <div class="mt-6">
        <%= render "relationships/follow"%>
      </div>
    </div>
  </div>

  <div class="flex items-center justify-between py-4 my-8 border-b">
    <% if user_signed_in? && current_user.id == @user.id %>
      <h1 class="text-xl font-bold mb-0 text-gray-500">あなたのタイマーグラフ</h1>
    <% else %>
      <h1 class="text-xl font-bold mb-0 text-gray-500"><%= @user.nickname %>さんのタイマーグラフ</h1>
    <% end %>
  </div>

  <!-- タブメニュー -->
  <section>
    <ul class="flex mb-0 list-none flex-wrap pt-3 pb-4 flex-row cursor-pointer">
      <li class="-mb-px mr-2 last:mr-0 flex-auto text-center">
        <a class="text-s font-bold uppercase px-5 py-3 shadow-lg rounded block leading-normal text-blue-500 bg-white hover:bg-blue-500 hover:text-white" id="StudyMenu">学習</a>
      </li>
      <li class="-mb-px mr-2 last:mr-0 flex-auto text-center">
        <a class="text-s font-bold uppercase px-5 py-3 shadow-lg rounded block leading-normal text-green-500 bg-white hover:bg-green-500 hover:text-white" id="RelaxMenu">リラックス</a>
      </li>
      <li class="-mb-px mr-2 last:mr-0 flex-auto text-center">
        <a class="text-s font-bold uppercase px-5 py-3 shadow-lg rounded block leading-normal text-red-400 bg-white hover:bg-red-400 hover:text-white" id="FitnessMenu">フィットネス</a>
      </li>
      <li class="-mb-px mr-2 last:mr-0 flex-auto text-center">
        <a class="text-s font-bold uppercase px-5 py-3 shadow-lg rounded block leading-normal text-purple-500 bg-white hover:bg-purple-500 hover:text-white" id="HobbyMenu">娯楽</a>
      </li>
    </ul>

    <div class="hidden" id="Study_timers_chart">
      <%= line_chart @study_timers.group(:genre).group_by_day(:created_at, last: 7).sum(:count), colors: ["#3182ce", "#63b3ed"], xtitle: "日付（直近一週間）", ytitle: "合計分数", curve: false, empty: "データがありません"%>
    </div>
    
    <div class="hidden" id="Relax_timers_chart">
      <%= line_chart @relax_timers.group(:genre).group_by_day(:created_at, last: 7).sum(:count), colors: ["#38a169", "#68d391"], xtitle: "日付（直近一週間）", ytitle: "合計セット数", curve: false, empty: "データがありません"%>
    </div>
    
    <div class="hidden" id="Fitness_timers_chart">
      <%= line_chart @fitness_timers.group(:genre).group_by_day(:created_at, last: 7).sum(:count), colors: ["#f56565", "#ecc94b"], xtitle: "日付（直近一週間）", ytitle: "合計セット数", curve: false, empty: "データがありません"%>
    </div>
    
    <div class="hidden" id="Hobby_timers_chart">
      <%= line_chart @hobby_timers.group(:genre).group_by_day(:created_at, last: 7).sum(:count), colors: ["#805ad5", "#d53f8c"], xtitle: "日付（直近一週間）", ytitle: "合計分数", curve: false, empty: "データがありません"%>
    </div>
  </section>


  <div class="flex items-center justify-between py-4 my-4 border-b">
    <% if user_signed_in? && current_user.id == @user.id %>
      <h1 class="text-xl font-bold mb-0 text-gray-500">あなたの投稿</h1>
    <% else %>
      <h1 class="text-xl font-bold mb-0 text-gray-500"><%= @user.nickname %>さんの投稿</h1>
    <% end %>
  </div>

  <div class="flex flex-wrap -m-5 py-2">
    <% @user.posts.each do |post| %>
      <div class="p-2 md:w-1/3">
        <div class="h-full overflow-hidden rounded border">
          <span class="inline-flex float-right text-sm font-thin p-2 mx-auto"><%= post.created_at.strftime('%Y/%m/%d')%></span>
          <div class="flex items-center">
            <%= link_to "/users/#{post.user.id}", title: "ユーザーページへ" do %>
              <% if post.user.avatar.present? %>
                <%= image_tag post.user.avatar, class:"inline-flex items-center justify-center p-2 mx-auto w-16 h-16 rounded-full flex-shrink-0 object-cover object-center"%>
                <span class="title-font font-medium"><%= post.user.nickname %></span>
              <% else %>
                <img alt="user" src="/images/user.jpeg" class="inline-flex p-2 w-16 h-16 rounded-full flex-shrink-0 object-cover object-center">
                <span class="title-font font-medium px-1"><%= post.user.nickname %></span>
              <% end %>
            <% end %>
          </div>

          <%= link_to post do %>    
            <% if post.feature_images.present? %>
              <%= image_tag post.feature_images[0], class:"lg:h-48 md:h-36 w-full object-cover object-center", alt:"blog"%>
            <% else %>
              <img class="lg:h-48 md:h-36 w-full object-cover object-center" src="https://dummyimage.com/720x400" alt="blog">
            <% end %>
          <% end %>

          <div class="pt-3 p-6">
            <%= render 'tags/tag_list', tag_list: post.tag_list %>
            <%= link_to post do %>
              <h1 class="title-font text-lg font-bold text-gray-900 mt-1 mb-3 whitespace-pre-wrap"><%= link_to post.title, post %></h1>
              <div class="overflow-auto h-20">
                <p class="leading-relaxed mb-3 whitespace-pre-wrap font-medium"><%= post.body %></p>
              </div>
            <% end %>
            <div class="flex items-center flex-wrap text-xl">
              <%= render 'likes/like', post: post %>
              <%= link_to post do %>
                <%= render 'comments/comment', post: post %>
              <% end %>
              <% if user_signed_in? && current_user.id == post.user_id %>
                <%= link_to edit_post_path(post), class: "mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none pr-3 py-1 hover:text-green-400", title:"編集" do %>
                  <i class="fas fa-edit"></i>
                <% end %>
                <%= link_to post, method: :delete, data: { confirm: 'ほんとに削除しますか？' }, class: "inline-flex items-center leading-none hover:text-red-600", title:"削除" do %>
                  <i class="fas fa-trash-alt"></i>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="flex items-center justify-center my-10">
    <%= paginate @posts %>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class="max-w-6xl m-auto">
  <div class="flex items-center justify-between py-4 my-4 border-b">
    <% if user_signed_in? && current_user.id == @user.id %>
      <h1 class="text-xl font-bold mb-0 text-gray-500">あなたがフォローしているユーザー</h1>
    <% else %>
      <h1 class="text-xl font-bold mb-0 text-gray-500"><%= @user.nickname %>さんがフォローしているユーザー</h1>
    <% end %>
  </div>

  <% @users.each do |user| %>
    <%= link_to "/users/#{user.id}", title: "ユーザーページへ" do %>
      <div class="flex item-center justify-center">
        <div class="bg-white shadow p-4 rounded lg:w-1/2">
          <div class="text-center mt-4">
            <p class="text-gray-600 font-bold"><%= user.nickname %></p>
          </div>
          <div class="flex justify-center mt-4">
            <% if user.avatar.present?%>
              <%= image_tag user.avatar, class:"p-2 mx-auto w-24 h-24 rounded-full flex-shrink-0 object-cover object-center"%>
            <% else %>
              <img alt="user" src="/images/user.jpeg" class="p-2 mx-auto w-16 h-16 rounded-full flex-shrink-0 object-cover object-center">
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/show_follower.html.erb
<div class="max-w-6xl m-auto">
  <div class="flex items-center justify-between py-4 my-4 border-b">
    <% if user_signed_in? && current_user.id == @user.id %>
      <h1 class="text-xl font-bold mb-0 text-gray-500">あなたをフォローしているユーザー</h1>
    <% else %>
      <h1 class="text-xl font-bold mb-0 text-gray-500"><%= @user.nickname %>さんをフォローしているユーザー</h1>
    <% end %>
  </div>
  
  <% @users.each do |user| %>
    <%= link_to "/users/#{user.id}", title: "ユーザーページへ" do %>
      <div class="flex item-center justify-center">
        <div class="bg-white shadow p-4 rounded lg:w-1/2">
          <div class="text-center mt-4">
            <p class="text-gray-600 font-bold"><%= user.nickname %></p>
          </div>
          <div class="flex justify-center mt-4">
            <% if user.avatar.present?%>
              <%= image_tag user.avatar, class:"p-2 mx-auto w-24 h-24 rounded-full flex-shrink-0 object-cover object-center"%>
            <% else %>
              <img alt="user" src="/images/user.jpeg" class="p-2 mx-auto w-16 h-16 rounded-full flex-shrink-0 object-cover object-center">
            <% end %>
          </div>
        </div>
      </div>  
    <% end %>
  <% end %>
</div>