config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: %i{show}, shallow: true do
    member do
      get :following, :followers
    end
  end
  # ゲストユーザー
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :relationships, only: %i[create destroy]

  
  resources :posts, shallow: true do
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resources :tags, only: %i{index}

  # タイマー機能用ルーティング
  get 'timers/study' => 'timers#study'
  get 'timers/relax' => 'timers#relax'
  get 'timers/fitness' => 'timers#fitness'
  get 'timers/hobby' => 'timers#hobby'
  post 'timers/study' => 'timers#study_create'
  post 'timers/relax' => 'timers#relax_create'
  post 'timers/fitness' => 'timers#fitness_create'
  post 'timers/hobby' => 'timers#hobby_create'
end

app/models/timer.rb
class Timer < ApplicationRecord
  with_options presence: true do
    validates :count, :genre
  end
  
  belongs_to :user
end

app/controllers/timers_controller.rb
class TimersController < ApplicationController
  before_action :authenticate_user!, only: %i[study_create relax_create fitness_create hobby_create]
  
  
  def study; end

  def relax; end

  def fitness; end

  def hobby; end

  def study_create
    @timer = Timer.new(timer_params)
    @timer.user_id = current_user.id
    if @timer.save
      flash[:notice] = '登録が完了しました。'
      redirect_to action: :study
    end
  end

  def relax_create
    @timer = Timer.new(timer_params)
    @timer.user_id = current_user.id
    if @timer.save
      flash[:notice] = "登録が完了しました。"
      redirect_to action: :relax
    end
  end

  def fitness_create
    @timer = Timer.new(timer_params)
    @timer.user_id = current_user.id
    if @timer.save
      flash[:notice] = "登録が完了しました。"
      redirect_to action: :fitness
    end
  end
  
  def hobby_create
    @timer = Timer.new(timer_params)
    @timer.user_id = current_user.id
    if @timer.save
      flash[:notice] = "登録が完了しました。"
      redirect_to action: :hobby
    end
  end

  private

  def timer_params
    params.permit(:count, :genre)
  end
end

app/helpers/timers_helper.rb
module TimersHelper
end

app/views/timers/_timer.html.erb
<div class="max-w-6xl m-auto">
  <!-- タイトル -->
  <div class="flex items-center justify-between pb-4 mb-4 border-b">
    <h1 class="text-xl font-bold mb-0 text-gray-500">これからの予定は？ </h1>
  </div>

  <!-- 予定 -->
  <section class="flex flex-wrap">
    <!-- 勉学 -->
    <div class="p-1 md:w-1/2 sm:w-full">
        <div class="shadow-lg group container rounded-md flex justify-center items-center mx-auto study">
            <div class="w-full image-cover rounded-t-md" >
              <div class="opacity-0 group-hover:opacity-100 text-center my-24">
                <span class="text-white tracking-wider leading-relaxed font-sans text-lg">学習</span> 
                <p class="text-white tracking-wider leading-relaxed font-sans">①ポモドーロ学習（25分学習✖︎5分休憩）</p>
                <p class="text-white tracking-wider leading-relaxed font-sans">②学生学習（50分学習✖︎10分休憩）</p>
                <div class="pt-4">
                  <%= link_to  "Learn more", timers_study_path, class:"rounded-lg p-2 bg-white text-gray-700 font-bold text-lg" %>  
                </div>
              </div>
            </div>
        </div>  
    </div>

    <!-- リラックス -->
    <div class="p-1 md:w-1/2 sm:w-full">
        <div class="shadow-lg group container rounded-md flex justify-center items-center mx-auto relax">
            <div class="w-full image-cover rounded-t-md" >
              <div class="opacity-0 group-hover:opacity-100 text-center my-24">
                <span class="text-white tracking-wider leading-relaxed font-sans">リラックス</span>
                <p class="text-white tracking-wider leading-relaxed font-sans">①ボックス呼吸（4秒✖︎4回呼吸サイクル）</p>
                <p class="text-white tracking-wider leading-relaxed font-sans">②レムサイクル仮眠（15分睡眠サイクル）</p>
                <div class="pt-4">
                  <%= link_to  "Learn more", timers_relax_path, class:"rounded-lg p-2 bg-white text-gray-700 font-bold text-lg" %>
                </div>
              </div>
          </div>
        </div>  
    </div>

    <!-- フィットネス -->
    <div class="p-1 md:w-1/2 sm:w-full">
        <div class="shadow-lg group container rounded-md flex justify-center items-center mx-auto fitness">
            <div  class="w-full image-cover rounded-t-md" >
              <div class="opacity-0 group-hover:opacity-100 text-center my-24">
                <span class="text-white tracking-wider leading-relaxed font-sans">フィットネス</span> 
                <p class="text-white tracking-wider leading-relaxed font-sans">①HIITトレーニング（30秒トレーニング✖︎10秒休憩サイクル）</p>
                <p class="text-white tracking-wider leading-relaxed font-sans">②ストレッチ・ヨガ（20秒間ストレッチサイクル）</p>
                <div class="pt-4">
                  <%= link_to  "Learn more", timers_fitness_path, class:"rounded-lg p-2 bg-white text-gray-700 font-bold text-lg" %>
                </div>
              </div>
          </div>
        </div>  
    </div>

    <!-- 趣味 -->
    <div class="p-1 md:w-1/2 sm:w-full">
        <div class="shadow-lg group container rounded-md flex justify-center items-center mx-auto hobby">
            <div class="w-full image-cover rounded-t-md" >
              <div class="opacity-0 group-hover:opacity-100 text-center my-24">
                <span class="text-white tracking-wider leading-relaxed font-sans">娯楽</span> 
                <p class="text-white tracking-wider leading-relaxed font-sans">①ゲーム（60分ゲーム✖︎10分休憩）</p>
                <p class="text-white tracking-wider leading-relaxed font-sans">②趣味（30分趣味✖︎5分気分転換）</p>
                <div class="pt-4">
                   <%= link_to  "Learn more", timers_hobby_path, class:"rounded-lg p-2 bg-white text-gray-700 font-bold text-lg" %>
                </div>
              </div>
          </div>
        </div>  
    </div>  
  </section>
</div>


<style>
  .study{
  background-image:url('/images/study.jpg');
  background-repeat: no-repeat;
  background-size: cover;
  background-position:center;
  }
  .study:hover{
    background-image:
    linear-gradient(to bottom right, rgba(0,0,70,0.8), rgba(28,181,224,0.8)),
    url('/images/study.jpg');
  }
  
  .relax{
  background-image:url('/images/relax.jpg');
  background-repeat: no-repeat;
  background-size: cover;
  background-position:center;
  }
  .relax:hover{
  background-image:
  linear-gradient(to bottom right,
  rgba(17,153,142,0.8), rgba(56,239,125,0.8) ),
  url('/images/relax.jpg');
  }
  
  .fitness{
  background-image:url('/images/fitness.jpg');
  background-repeat: no-repeat;
  background-size: cover;
  background-position:center;
  }
  .fitness:hover{
  background-image:
  linear-gradient(to bottom right,
  rgba(241,39,17,0.8), rgba(245,175,25,0.8) ),
  url('/images/fitness.jpg');
  }
  
  .hobby{
  background-image:url('/images/hobby.jpg');
  background-repeat: no-repeat;
  background-size: cover;
  background-position:center;
  }
  .hobby:hover{
  background-image:
  linear-gradient(to bottom right,
  rgba(3,0,30,0.8), rgba(115,3,192,0.8), rgba(236,56,188,0.8), rgba(253,239,249,0.8) ),
  url('/images/hobby.jpg');
  }

  .image-cover  {
  height:300px;
  }
</style>
        
        

app/views/timers/fitness.html.erb
<div class="container px-5 py-24 mx-auto flex flex-wrap flex-col">
  <!-- タブメニューー -->
  <ul class="flex mb-0 list-none flex-wrap pt-3 pb-4 flex-row cursor-pointer">
    <li class="-mb-px mr-2 last:mr-0 flex-auto text-center">
      <a class="text-s font-bold uppercase px-5 py-3 shadow-lg rounded block leading-normal text-red-500 bg-white hover:bg-red-500 hover:text-white" id="HiitMenu">HIITトレーニング</a>
    </li>
    <li class="-mb-px mr-2 last:mr-0 flex-auto text-center">
      <a class="text-s font-bold uppercase px-5 py-3 shadow-lg rounded block leading-normal text-yellow-500 bg-white hover:bg-yellow-500 hover:text-white" id="StretchMenu">ストレッチ・ヨガ</a>
    </li>
  </ul>
  
  <!-- HIITタイマー -->
  <section class="bg-red-500 border rounded hidden h-auto" id="Hiit">
    <!-- タイマー -->
    <div class="m-auto w-1/2 h-4 mt-4" id="HiitBar"></div>
    <div class="max-w-2xl text-6xl text-center m-auto p-10">
      <div id="HiitTimer">00:30</div>
      <div id="HiitStart" class="btn btn-default">Start</div>
      <div id="HiitReset" class="btn btn-default hidden"></div>
    </div>   

    <div class="flex item-center justify-center">
      <%= form_with model: @timer, local: true do |form| %>
        <div class="inline-flex">
          <%= form.text_field :genre, class: "hidden", value: "HIITトレーニング" %>
          <div class="relative flex w-full flex-wrap items-stretch mb-3">
            <span class="cursor-pointer z-10 leading-snug font-normal absolute text-center text-gray-400 absolute bg-transparent rounded text-base items-center justify-center py-1 pl-1" id="HiitEdit" title="編集する"><i class="fas fa-edit"></i></span>
            <%= form.number_field :count, min: 0, max: 600, readonly: true, id: "HiitTime", class:"relative rounded text-sm shadow outline-none focus:outline-none focus:shadow-outline w-20 h-8 pl-10" %>
            <p class="text-xl">✖︎セット</p>
          </div>
        </div>
        <% if user_signed_in? %>
          <div class="flex text-center justify-center p-10">
            <%= form.submit disabled: true, id: "HiitSave", value: "記録する", class: "p-2 rounded" %>
          </div>
        <% end %>
      <% end %>
    </div>
    <!-- モーダルウィンドウ -->
    <div class="text-center m-auto p-10">
      <div id="HiitOpen"></div>
      <p id="HiitRest"></p>
      <p id="HiitKeep"></p>
    </div> 
  </section>
  
  <!-- ストレッチタイマー -->
  <section class="bg-yellow-500 border rounded hidden" id="Stretch">
    <!-- タイマー -->
    <div class="m-auto w-1/2 h-4 mt-4" id="StretchBar"></div>
    <div class="max-w-2xl text-6xl text-center m-auto p-10">
      <div id="StretchTimer">00:20</div>
      <div id="StretchStart" class="btn btn-default">Start</div>
      <div id="StretchReset" class="btn btn-default hidden"></div>
    </div>

    <div class="flex item-center justify-center">
      <%= form_with model: @timer, local: true do |form| %>
        <div class="inline-flex">
          <%= form.text_field :genre, class: "hidden", value: "ストレッチ・ヨガ" %>
          <div class="relative flex w-full flex-wrap items-stretch mb-3">
            <span class="cursor-pointer z-10 leading-snug font-normal absolute text-center text-gray-400 absolute bg-transparent rounded text-base items-center justify-center py-1 pl-1" id="StretchEdit" title="編集する"><i class="fas fa-edit"></i></span>
            <%= form.number_field :count, min: 0, max: 600, readonly: true, id: "StretchTime", class:"relative rounded text-sm shadow outline-none focus:outline-none focus:shadow-outline w-20 h-8 pl-10" %>
            <p class="text-xl">✖︎セット</p>
          </div>
        </div>
        <% if user_signed_in? %>
          <div class="flex text-center justify-center p-10">
            <%= form.submit disabled: true, id: "StretchSave", value: "記録する", class: "p-2 rounded" %>
          </div>
        <% end %>
      <% end %>
    </div>
    <!-- モーダルウィンドウ -->
    <div class="text-center m-auto p-10">
      <div id="StretchOpen"></div>
      <p id="StretchRest"></p>
      <p id="StretchKeep"></p>
    </div>     
  </section>
</div>

app/views/timers/hobby.html.erb
<div class="container px-5 py-24 mx-auto flex flex-wrap flex-col">
  <!-- タブメニューー -->
  <ul class="flex mb-0 list-none flex-wrap pt-3 pb-4 flex-row cursor-pointer">
    <li class="-mb-px mr-2 last:mr-0 flex-auto text-center">
      <a class="text-s font-bold uppercase px-5 py-3 shadow-lg rounded block leading-normal text-purple-600 bg-white hover:bg-purple-600 hover:text-white" id="GameMenu">ゲーム</a>
    </li>
    <li class="-mb-px mr-2 last:mr-0 flex-auto text-center">
      <a class="text-s font-bold uppercase px-5 py-3 shadow-lg rounded block leading-normal text-pink-600 bg-white hover:bg-pink-600 hover:text-white" id="HobbyMenu">趣味</a>
    </li>
  </ul>
  
  <!-- ゲームタイマー -->
  <section class="bg-purple-600 border rounded hidden" id="Game">
    <!-- タイマー -->
    <div class="m-auto w-1/2 h-4 mt-4" id="GameBar"></div>
    <div class="max-w-2xl text-6xl text-center m-auto p-10">
      <div id="GameTimer">60:00</div>
      <div id="GameStart" class="btn btn-default">Start</div>
      <div id="GameReset" class="btn btn-default hidden"></div>
    </div>   
   
    <div class="flex item-center justify-center">
      <%= form_with model: @timer, local: true do |form| %>
        <div class="inline-flex">
          <%= form.text_field :genre, class: "hidden", value: "ゲーム" %>
          <div class="relative flex w-full flex-wrap items-stretch mb-3">
            <span class="cursor-pointer z-10 leading-snug font-normal absolute text-center text-gray-400 absolute bg-transparent rounded text-base items-center justify-center py-1 pl-1" id="GameEdit" title="編集する"><i class="fas fa-edit"></i></span>
            <%= form.number_field :count, min: 0, max: 600, readonly: true, id: "GameTime", class:"relative rounded text-sm shadow outline-none focus:outline-none focus:shadow-outline w-20 h-8 pl-10" %>
            <p class="text-xl">✖︎分</p>
          </div>
        </div>
        <% if user_signed_in? %>
          <div class="flex text-center justify-center p-10">
            <%= form.submit disabled: true, id: "GameSave", value: "記録する", class: "p-2 rounded" %>
          </div>
        <% end %>
      <% end %>
    </div>
    <!-- モーダルウィンドウ -->
    <div class="text-center m-auto p-10">
      <div id="GameOpen"></div>
      <div id="GameMask" class="fixed bg-gray-500 bg-opacity-75 inset-0 hidden z-0"></div>
      <section id="GameModal" class="bg-white w-1/4 absolute border rounded-lg p-10 inset-x-0 top-1/4 m-auto hidden">
        <p class="">時間があっという間でした</p>
        <p id="GameRest" class="btn btn-default mt-4">目の休憩</p>
        <p id="GameKeep" class="btn btn-default mt-4">もっと楽しむ</p>
      </section>   
    </div> 
  </section>
  
  <!-- 趣味タイマー -->
  <section class="bg-pink-600 border rounded hidden" id="Hobby">
    <!-- タイマー -->
    <div class="m-auto w-1/2 h-4 mt-4" id="HobbyBar"></div>
    <div class="max-w-2xl text-6xl text-center m-auto p-10 ">
      <div id="HobbyTimer">30:00</div>
      <div id="HobbyStart" class="btn btn-default">Start</div>
      <div id="HobbyReset" class="btn btn-default hidden"></div>
    </div>

    <div class="flex item-center justify-center">
      <%= form_with model: @timer, local: true do |form| %>
        <div class="inline-flex">
          <%= form.text_field :genre, class: "hidden", value: "趣味" %>
          <div class="relative flex w-full flex-wrap items-stretch mb-3">
            <span class="cursor-pointer z-10 leading-snug font-normal absolute text-center text-gray-400 absolute bg-transparent rounded text-base items-center justify-center py-1 pl-1" id="HobbyEdit" title="編集する"><i class="fas fa-edit"></i></span>
            <%= form.number_field :count, min: 0, max: 600, readonly: true, id: "HobbyTime", class:"relative rounded text-sm shadow outline-none focus:outline-none focus:shadow-outline w-20 h-8 pl-10" %>
            <p class="text-xl">✖︎分</p>
          </div>
        </div>
        <% if user_signed_in? %>
          <div class="flex text-center justify-center p-10">
            <%= form.submit disabled: true, id: "HobbySave", value: "記録する", class: "p-2 rounded" %>
          </div>
        <% end %>
      <% end %>
    </div>
    <!-- モーダルウィンドウ -->
    <div class="text-center m-auto p-10">
      <div id="HobbyOpen"></div>
      <div id="HobbyMask" class="fixed bg-gray-500 bg-opacity-75 inset-0 hidden z-0"></div>
      <section id="HobbyModal" class="bg-white w-1/4 absolute border rounded-lg p-10 inset-x-0 top-1/4 m-auto hidden">
        <p class="">時間があっという間でした</p>
        <p id="HobbyRest" class="btn btn-default mt-4">気分転換</p>
        <p id="HobbyKeep" class="btn btn-default mt-4">もっと楽しむ</p>
      </section>   
    </div>     
  </section>
</div>

app/views/timers/relax.html.erb
<div class="container px-5 py-24 mx-auto flex flex-wrap flex-col">
  <!-- タブメニューー -->
  <ul class="flex mb-0 list-none flex-wrap pt-3 pb-4 flex-row cursor-pointer">
    <li class="-mb-px mr-2 last:mr-0 flex-auto text-center">
      <a class="text-s font-bold uppercase px-5 py-3 shadow-lg rounded block leading-normal text-green-600 bg-white hover:bg-green-600 hover:text-white" id="BoxBreathingMenu">ボックス呼吸</a>
    </li>
    <li class="-mb-px mr-2 last:mr-0 flex-auto text-center">
      <a class="text-s font-bold uppercase px-5 py-3 shadow-lg rounded block leading-normal text-green-400 bg-white hover:bg-green-400 hover:text-white" id="RemSleepMenu">レムサイクル仮眠</a>
    </li>
  </ul>
  
  <!-- ボックス呼吸法タイマー -->
  <section class="bg-green-600 border rounded hidden" id="BoxBreathing">
    <!-- タイマー -->
    <div class="m-auto w-1/2 h-4 mt-4" id="BoxBreathingBar"></div>
    <div class="max-w-2xl text-6xl text-center m-auto p-10">
      <div id="BoxBreathingTimer">00:04</div>
      <div id="BoxBreathingStart" class="btn btn-default">Start</div>
      <div id="BoxBreathingReset" class="btn btn-default hidden"></div>
    </div>   
   
    <div class="flex item-center justify-center">
      <%= form_with model: @timer, local: true do |form| %>
        <div class="inline-flex">
          <%= form.text_field :genre, class: "hidden", value: "ボックス呼吸" %>
          <div class="relative flex w-full flex-wrap items-stretch mb-3">
            <span class="cursor-pointer z-10 leading-snug font-normal absolute text-center text-gray-400 absolute bg-transparent rounded text-base items-center justify-center py-1 pl-1" id="BoxBreathingEdit" title="編集する"><i class="fas fa-edit"></i></span>
            <%= form.number_field :count, min: 0, max: 600, readonly: true, id: "BoxBreathingTime", class:"relative rounded text-sm shadow outline-none focus:outline-none focus:shadow-outline w-20 h-8 pl-10" %>
            <p class="text-xl">✖︎セット</p>
          </div>
        </div>
        <% if user_signed_in? %>
          <div class="flex text-center justify-center p-10">
            <%= form.submit disabled: true, id: "BoxBreathingSave", value: "記録する", class: "p-2 rounded" %>
          </div>
        <% end %>
      <% end %>
    </div>
    
    <!-- モーダルウィンドウ -->
    <div class="text-center m-auto p-10">
      <div id="BoxBreathingOpen"></div>
      <div id="BoxBreathingMask" class="fixed bg-gray-500 bg-opacity-75 inset-0 hidden z-0"></div>
      <section id="BoxBreathingModal" class="bg-white w-1/4 absolute border rounded-lg p-10 inset-x-0 top-1/4 m-auto hidden">
        <p class=""></p>
        <p id="BoxBreathingRest" class="btn btn-default mt-4"></p>
        <p id="BoxBreathingKeep" class="btn btn-default mt-4"></p>
      </section>   
    </div> 
  </section>
  
  <!-- レム仮眠・昼寝タイマー -->
  <section class="bg-green-400 border rounded hidden" id="RemSleep">
    <!-- タイマー -->
    <div class="m-auto w-1/2 h-4 mt-4" id="RemSleepBar"></div>
    <div class="max-w-2xl text-6xl text-center m-auto p-10 ">
      <div id="RemSleepTimer">15:00</div>
      <div id="RemSleepStart" class="btn btn-default">Start</div>
      <div id="RemSleepReset" class="btn btn-default hidden"></div>
    </div>

    <div class="flex item-center justify-center">
      <%= form_with model: @timer, local: true do |form| %>
        <div class="inline-flex">
          <%= form.text_field :genre, class: "hidden", value: "レムサイクル仮眠" %>
          <div class="relative flex w-full flex-wrap items-stretch mb-3">
            <span class="cursor-pointer z-10 leading-snug font-normal absolute text-center text-gray-400 absolute bg-transparent rounded text-base items-center justify-center py-1 pl-1" id="RemSleepEdit" title="編集する"><i class="fas fa-edit"></i></span>
            <%= form.number_field :count, min: 0, max: 600, readonly: true, id: "RemSleepTime", class:"relative rounded text-sm shadow outline-none focus:outline-none focus:shadow-outline w-20 h-8 pl-10" %>
            <p class="text-xl">✖︎セット</p>
          </div>
        </div>
          <% if user_signed_in? %>
          <div class="flex text-center justify-center p-10">
            <%= form.submit disabled: true, id: "RemSleepSave", value: "記録する", class: "p-2 rounded" %>
          </div>
        <% end %> 
      <% end %>
    </div>
    <!-- モーダルウィンドウ -->
    <div class="text-center m-auto p-10">
      <div id="RemSleepOpen"></div>
      <div id="RemSleepMask" class="fixed bg-gray-500 bg-opacity-75 inset-0 hidden z-0"></div>
      <section id="RemSleepModal" class="bg-white w-1/4 absolute border rounded-lg p-10 inset-x-0 top-1/4 m-auto hidden">
        <p class="">おはようございます</p>
        <p id="RemSleepRest" class="btn btn-default mt-4">元気になった！！</p>
        <p id="RemSleepKeep" class="btn btn-default mt-4">あと少し寝る...</p>
      </section>   
    </div>     
  </section>
</div>

app/views/timers/study.html.erb
<div class="container px-5 py-24 mx-auto flex flex-wrap flex-col">
  <!-- タブメニューー -->
  <ul class="flex mb-0 list-none flex-wrap pt-3 pb-4 flex-row cursor-pointer">
    <li class="-mb-px mr-2 last:mr-0 flex-auto text-center">
      <a class="text-s font-bold uppercase px-5 py-3 shadow-lg rounded block leading-normal text-blue-600 bg-white hover:bg-blue-600 hover:text-white" id="PomodoroMenu">ポモドーロ学習</a>
    </li>
    <li class="-mb-px mr-2 last:mr-0 flex-auto text-center">
      <a class="text-s font-bold uppercase px-5 py-3 shadow-lg rounded block leading-normal text-blue-400 bg-white hover:bg-blue-400 hover:text-white" id="StudentMenu">学生学習</a>
    </li>
  </ul>
  
  <!-- ポモドーロ・テクニックタイマー -->
  <section class="bg-blue-600 border rounded hidden" id="Pomodoro">
    <!-- タイマー -->
    <div class="m-auto w-1/2 h-4 mt-4" id="PomodoroBar"></div>
    <div class="max-w-2xl text-6xl text-center m-auto p-10">
      <div id="PomodoroTimer">25:00</div>
      <div id="PomodoroStart" class="btn btn-default">Start</div>
      <div id="PomodoroReset" class="btn btn-default hidden"></div>
    </div>   
    

    <div class="flex item-center justify-center">
      <%= form_with model: @timer, local: true do |form| %>
        <div class="inline-flex">
          <%= form.text_field :genre, class: "hidden", value: "ポモドーロ学習" %>
          <div class="relative flex w-full flex-wrap items-stretch mb-3">
            <span class="cursor-pointer z-10 leading-snug font-normal absolute text-center text-gray-400 absolute bg-transparent rounded text-base items-center justify-center py-1 pl-1" id="PomodoroEdit" title="編集する"><i class="fas fa-edit"></i></span>
            <%= form.number_field :count, min: 0, max: 600, readonly: true, id: "PomodoroTime", class:"relative rounded text-sm shadow outline-none focus:outline-none focus:shadow-outline w-20 h-8 pl-10" %>
            <p class="text-xl">✖︎分</p>
          </div>
        </div>
        <% if user_signed_in? %>
          <div class="flex text-center justify-center p-10">
            <%= form.submit disabled: true, id: "PomodoroSave", value: "記録する", class: "p-2 rounded" %>
          </div>
        <% end %>
      <% end %>
    </div>
    <!-- モーダルウィンドウ -->
    <div class="text-center m-auto p-10">
      <div id="PomodoroOpen"></div>
      <div id="PomodoroMask" class="fixed bg-gray-500 bg-opacity-75 inset-0 hidden z-0"></div>
      <section id="PomodoroModal" class="bg-white w-1/4 absolute border rounded-lg p-10 inset-x-0 top-1/4 m-auto hidden">
        <p class="">お疲れ様です</p>
        <p id="PomodoroRest" class="btn btn-default mt-4">休憩する</p>
        <p id="PomodoroKeep" class="btn btn-default mt-4">もっと頑張る</p>
      </section>   
    </div> 
  </section>
  
  <!-- 学生生活タイマー -->
  <section class="bg-blue-400 border rounded hidden" id="Student">
    <!-- タイマー -->
    <div class="m-auto w-1/2 h-4 mt-4" id="StudentBar"></div>
    <div class="max-w-2xl text-6xl text-center m-auto p-10 ">
      <div id="StudentTimer">50:00</div>
      <div id="StudentStart" class="btn btn-default">Start</div>
      <div id="StudentReset" class="btn btn-default hidden"></div>
    </div>
    
    <div class="flex item-center justify-center">
      <%= form_with model: @timer, local: true do |form| %>
        <div class="inline-flex">
          <%= form.text_field :genre, class: "hidden", value: "学生学習" %>
          <div class="relative flex w-full flex-wrap items-stretch mb-3">
            <span class="cursor-pointer z-10 leading-snug font-normal absolute text-center text-gray-400 absolute bg-transparent rounded text-base items-center justify-center py-1 pl-1" id="StudentEdit" title="編集する"><i class="fas fa-edit"></i></span>
            <%= form.number_field :count, min: 0, max: 600, readonly: true, id: "StudentTime", class:"relative rounded text-sm shadow outline-none focus:outline-none focus:shadow-outline w-20 h-8 pl-10" %>
            <p class="text-xl">✖︎分</p>
          </div>
        </div>
        <% if user_signed_in? %>
          <div class="flex text-center justify-center p-10">
            <%= form.submit disabled: true, id: "StudentSave", value: "記録する", class: "p-2 rounded" %>
          </div>
        <% end %>
      <% end %>
    </div>
    <!-- モーダルウィンドウ -->
    <div class="text-center m-auto p-10">
      <div id="StudentOpen"></div>
      <div id="StudentMask" class="fixed bg-gray-500 bg-opacity-75 inset-0 hidden z-0"></div>
      <section id="StudentModal" class="bg-white w-1/4 absolute border rounded-lg p-10 inset-x-0 top-1/4 m-auto hidden">
        <p class="">お疲れ様です</p>
        <p id="StudentRest" class="btn btn-default mt-4">休憩する</p>
        <p id="StudentKeep" class="btn btn-default mt-4">もっと頑張る</p>
      </section>   
    </div>     
  </section>
</div>