config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: %i{show}, shallow: true do
    member do
      get :following, :followers
    end
  end
  # ゲストユーザー
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :relationships, only: %i[create destroy]

  
  resources :posts, shallow: true do
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resources :tags, only: %i{index}

  # タイマー機能用ルーティング
  get 'timers/study' => 'timers#study'
  get 'timers/relax' => 'timers#relax'
  get 'timers/fitness' => 'timers#fitness'
  get 'timers/hobby' => 'timers#hobby'
  post 'timers/study' => 'timers#study_create'
  post 'timers/relax' => 'timers#relax_create'
  post 'timers/fitness' => 'timers#fitness_create'
  post 'timers/hobby' => 'timers#hobby_create'
end

app/models/post.rb
class Post < ApplicationRecord
  # Postモデルバリデーション制限
  with_options presence: true do
    validates :title, length: { maximum: 30 }
    validates :body, length: { maximum: 140 }
  end

  validates :feature_images, content_type: ['image/png', 'image/jpg', 'image/jpeg', 'image/gif'], limit: { max: 4 }
  
  

  # Postモデルアソシエーション
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many_attached :feature_images, dependent: :destroy
  
  # タグ関連付け
  acts_as_taggable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_post, only: %i[show edit update destroy]

  def index
    # N+1問題対策
    @posts = Post.with_attached_feature_images.includes(:user, :likes, :comments, :taggings).order('created_at DESC').page(params[:page]).without_count.per(15)
    @tags = Post.tags_on(:tags).most_used(20)
    # タグ投稿絞り
    if params[:tag_list]
      @posts = Post.with_attached_feature_images.tagged_with(params[:tag_list]).includes(:user, :likes, :comments, :taggings).order('created_at DESC').page(params[:page]).per(15)
      @tag = params[:tag_list]
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order('created_at DESC').page(params[:page]).per(10)
  end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: '作成できました。' }
        format.json { render :index, status: :created }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: '更新できました。' }
        format.json { render :index, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: '削除できました。' }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :tag_list, feature_images: [])
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, multipart: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "エラー") %>がございます。</h2>
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :タイトル（最大30字まで）, class: "relative" %>
      <span class="absolute text-red-600">*</span>
    <%= form.text_field :title, class: "input", maxlength:'30'%>
  </div>

  <div class="mb-6">
    <%= form.label :本文（最大140字まで）, class: "relative" %>
      <span class="absolute text-red-600">*</span>
    <%= form.text_area :body, class: "input", maxlength:'140', rows: '5'%>
  </div>

  <div class="mb-6">
    <%= form.label :タグ（最大20文字まで）, class: "relative" %>
    <%= form.text_field :tag_list, class: "input", value: @post.tag_list.join("、"), maxlength:'20', placeholder: "スポーツ、趣味..." %>
  </div>

  <div class="mb-6">
    <%= form.label :画像（最大４枚まで、１枚目はサムネになります）, class: "label" %>
    <%= form.file_field :feature_images, accept: 'image/jpg,image/jpeg,image/png,image/gif', multiple: true, class: ""%>
  </div>
  

  <div class="mb-6">
    <%= form.submit "作成する", class: "btn-default btn w-1/2 flex item-center justify-center m-auto" %>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<div class="flex flex-wrap -m-5 py-2">
  <% @search_posts.each do |post| %>
    <div class="p-2 md:w-1/3">
      <div class="h-full overflow-hidden rounded border">
        <span class="inline-flex float-right text-sm font-thin p-2 mx-auto"><%= post.created_at.strftime('%Y/%m/%d')%></span>
        <div class="flex items-center">
          <%= link_to "/users/#{post.user.id}", title: "ユーザーページへ" do %>
            <% if post.user.avatar.present? %>
              <%= image_tag post.user.avatar, class:"inline-flex items-center justify-center p-2 mx-auto w-16 h-16 rounded-full flex-shrink-0 object-cover object-center"%>
              <span class="title-font font-medium"><%= post.user.nickname %></span>
            <% else %>
              <img alt="user" src="/images/user.jpeg" class="inline-flex p-2 w-16 h-16 rounded-full flex-shrink-0 object-cover object-center">
              <span class="title-font font-medium px-1"><%= post.user.nickname %></span>
            <% end %>
          <% end %>
        </div>

        <%= link_to post do %>    
          <% if post.feature_images.present? %>
            <%= image_tag post.feature_images[0], class:"lg:h-48 md:h-36 w-full object-cover object-center", alt:"blog"%>
          <% else %>
            <img class="lg:h-48 md:h-36 w-full object-cover object-center" src="https://dummyimage.com/720x400" alt="blog">
          <% end %>
        <% end %>

        <div class="pt-3 p-6">
          <%= render 'tags/tag_list', tag_list: post.tag_list %>
          <%= link_to post do %>
            <h1 class="title-font text-lg font-bold text-gray-900 mt-1 mb-3 whitespace-pre-wrap"><%= link_to post.title, post %></h1>
            <div class="overflow-auto h-20">
              <p class="leading-relaxed mb-3 whitespace-pre-wrap font-medium"><%= post.body %></p>
            </div>
          <% end %>
          <div class="flex items-center flex-wrap text-xl">
            <%= render 'likes/like', post: post %>
            <%= link_to post do %>
              <%= render 'comments/comment', post: post %>
            <% end %>
            <% if user_signed_in? && current_user.id == post.user_id %>
              <%= link_to edit_post_path(post), class: "mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none pr-3 py-1 hover:text-green-400", title:"編集" do %>
                <i class="fas fa-edit" id="編集"></i>
              <% end %>
              <%= link_to post, method: :delete, data: { confirm: 'ほんとに削除しますか？' }, class: "inline-flex items-center leading-none hover:text-red-600", title:"削除" do %>
                <i class="fas fa-trash-alt" id="削除"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="post-next flex items-center justify-center my-10">
  <%= link_to_next_page @posts, '次のページ', class: "next hidden" %>
  <%= paginate @posts if params[:tag_list] %>
</div>

app/views/posts/edit.html.erb
<div class="max-w-2xl m-auto">
  <h1>投稿編集</h1>

  <%= render 'form', post: @post %>

<%= link_to '変更せず戻る', posts_path, class: "btn-default btn w-1/2 flex item-center justify-center m-auto mb-6" %>
<%= link_to '削除', @post, method: :delete, data: { confirm: 'ほんとに削除しますか？' }, class: "btn-default btn w-1/2 flex item-center justify-center m-auto mb-6 btn btn-red" %></td>
</div>

app/views/posts/index.html.erb
<div class="max-w-6xl m-auto">
  <!-- タイマーテンプレート -->
  <%= render partial: "timers/timer" %>
  
  <div class="flex items-center justify-between py-4 my-4 border-b">
    <% if params[:tag_list] %>
      <h1 class="text-xl font-bold mb-0 text-gray-500"><%= "##{@tag}についての投稿" %></h1>
    <% else %>
      <h1 class="text-xl font-bold mb-0 text-gray-500">投稿一覧</h1>
    <% end %>
    <%= link_to "新規投稿", new_post_path, class: "btn btn-default" if user_signed_in? %>
  </div>

  <div class="mb-8">
    <i class="fas fa-tags"></i>
    <h2 class="inline mr-1">Top 20</h2>
    <% @tags.each do |tag| %>
      <%= link_to posts_path(tag_list: tag.name) do %>
        <span class="inline-block py-1 px-2 border rounded-full text-indigo-500 text-xs font-medium tracking-widest hover:bg-indigo-500 hover:text-white"><%= "##{tag.name}(#{tag.taggings_count})" %></span>
      <% end %>
    <% end %>
    <%= link_to "全てのタグ", tags_path, class: "inline-block py-1 px-2 border rounded-full text-indigo-500 text-xs font-medium tracking-widest hover:bg-indigo-500 hover:text-white" %>
  </div>
  
  <div class="container mx-auto jscroll">
    <%= render partial: 'posts/posts', post: @post %>
  </div>

<!-- ページトップへ戻るボタン -->
  <p class="pagetop fixed bottom-1/10 right-1/10 block hidden" title="トップへ戻る">
    <a href="#" class="block text-center bg-indigo-500 rounded-full h-12 w-12 flex items-center justify-center"><i class="fas fa-chevron-up text-white text-xl"></i></a>
  </p>
  
</div>

app/views/posts/new.html.erb
<div class="max-w-2xl m-auto">

<h1>新規投稿</h1>

<%= render 'form', post: @post %>

<%= link_to '戻る', posts_path, class:"btn-default btn w-1/2 flex item-center justify-center m-auto" %>

</div>

app/views/posts/show.html.erb
<div class="max-w-6xl m-auto">
  <div class="container mx-auto border rounded-lg p-4 mb-8">
    <%= link_to "/users/#{@post.user.id}", title: "ユーザーページへ", class:"inline-flex items-center" do %>
      <% if @post.user.avatar.present? %>
        <%= image_tag @post.user.avatar, class:"flex items-center justify-center p-2 mx-auto w-16 h-16 rounded-full flex-shrink-0 object-cover object-center"%>
      <% else %>
        <img alt="user" src="/images/user.jpeg" class="w-10 h-10 rounded-full flex-shrink-0 object-cover object-center">
      <% end %>
      <span class="title-font font-medium px-2"><%= @post.user.nickname %></span>
    <% end %>
    <span class="float-right text-sm px-2 py-4 mx-auto"><%= @post.created_at.strftime('%Y/%m/%d')%></span>
    <div>
      <% if @post.feature_images.present? %>
        <% @post.feature_images.each do |image| %>
            <%= link_to image, 'data-lightbox': image do %>
              <%= image_tag image, class:"p-1" %>
            <% end %>
        <% end %>
      <% end %>
    </div>


    <div class="px-4 py-4">
      <%= render 'tags/tag_list', tag_list: @post.tag_list %>
      <h1 class="title-font text-lg font-bold text-gray-900 mb-3 whitespace-pre-wrap"><%= @post.title %></h1>
      <p class="leading-relaxed mb-3 whitespace-pre-wrap font-medium"><%= @post.body %></p>
    </div>
    <div class="flex items-center flex-wrap text-xl">
      <%= render 'likes/like', post: @post %>
      <%= render 'comments/comment', post: @post %>

      <% if user_signed_in? && current_user.id == @post.user_id %>
        <%= link_to edit_post_path(@post), class: "mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none pr-3 py-1 hover:text-green-400", title:"編集" do %>
          <i class="fas fa-edit"></i>
        <% end %>
        <%= link_to @post, method: :delete, data: { confirm: 'ほんとに削除しますか？' }, class: "inline-flex items-center leading-none hover:text-red-600", title:"削除" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  
  <% if user_signed_in? %>
    <div class="">
      <%= form_with(model: [@post, @comment], remote: true) do |form| %>
        <div class="mt-6">
          <%= form.text_area :body, class: "input mt-4", placeholder: "(最大140文字まで)", maxlength:'140', rows: "1" %>
        </div>
        <div class="mb-6">
          <%= form.submit "コメントする", class: "btn-default btn" %>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="flex items-center justify-between pb-4 mb-4 border-b">
    <h1 class="text-xl font-bold mb-0 text-gray-500">コメント</h1>
  </div>
  <div id="comment-list">
    <%= render 'comments/comments', comments: @comments %>
  </div>
    <%= link_to_next_page @comments, 'もっと見る・・・', id: 'more-comment', class: 'more-link flex items-center justify-center inline-block py-1 px-2 border rounded-lg text-indigo-500 font-medium tracking-widest hover:bg-indigo-500 hover:text-white', remote: true%>
</div>

app/views/posts/show.js.erb
$('#comment-list').append("<%= j(render 'comments/comments', comments: @comments) %>")
$("#more-comment").replaceWith("<%= j(
  link_to_next_page(@comments, 'もっと見る・・・', id: 'more-comment', class: 'more-link flex items-center justify-center inline-block py-1 px-2 border rounded-lg text-indigo-500 font-medium tracking-widest hover:bg-indigo-500 hover:text-white', remote: true)
) %>");